(function($){$.fn.dcAccordion=function(options){var defaults={classParent:'dcjq-parent',classActive:'active',classArrow:'dcjq-icon',classCount:'dcjq-count',classExpand:'dcjq-current-parent',classDisable:'',eventType:'click',hoverDelay:300,menuClose:true,autoClose:true,autoExpand:false,speed:'slow',saveState:true,disableLink:true,showCount:false,cookie:'dcjq-accordion'};var options=$.extend(defaults,options);this.each(function(options){var obj=this;$objLinks=$('li > a',obj);$objSub=$('li > ul',obj);if(defaults.classDisable){$objLinks=$('li:not(.'+defaults.classDisable+') > a',obj);$objSub=$('li:not(.'+defaults.classDisable+') > ul',obj);}
classActive=defaults.classActive;setUpAccordion();if(defaults.saveState==true){checkCookie(defaults.cookie,obj,classActive);}
if(defaults.autoExpand==true){$('li.'+defaults.classExpand+' > a').addClass(classActive);}
resetAccordion();if(defaults.eventType=='hover'){var config={sensitivity:2,interval:defaults.hoverDelay,over:linkOver,timeout:defaults.hoverDelay,out:linkOut};$objLinks.hoverIntent(config);var configMenu={sensitivity:2,interval:1000,over:menuOver,timeout:1000,out:menuOut};$(obj).hoverIntent(configMenu);if(defaults.disableLink==true){$objLinks.click(function(e){if($(this).siblings('ul').length>0){e.preventDefault();}});}}else{$objLinks.click(function(e){$activeLi=$(this).parent('li');$parentsLi=$activeLi.parents('li');$parentsUl=$activeLi.parents('ul');if(defaults.disableLink==true){if($(this).siblings('ul').length>0){e.preventDefault();}}
if(defaults.autoClose==true){autoCloseAccordion($parentsLi,$parentsUl);}
if($('> ul',$activeLi).is(':visible')){$('ul',$activeLi).slideUp(defaults.speed);$('a',$activeLi).removeClass(classActive);}else{$(this).siblings('ul').slideToggle(defaults.speed);$('> a',$activeLi).addClass(classActive);}
if(defaults.saveState==true){createCookie(defaults.cookie,obj,classActive);}});}
function setUpAccordion(){$arrow='<span class="'+defaults.classArrow+'"></span>';var classParentLi=defaults.classParent+'-li';$objSub.show();$('li',obj).each(function(){if($('> ul',this).length>0){$(this).addClass(classParentLi);$('> a',this).addClass(defaults.classParent).append($arrow);}});$objSub.hide();if(defaults.classDisable){$('li.'+defaults.classDisable+' > ul').show();}
if(defaults.showCount==true){$('li.'+classParentLi,obj).each(function(){if(defaults.disableLink==true){var getCount=parseInt($('ul a:not(.'+defaults.classParent+')',this).length);}else{var getCount=parseInt($('ul a',this).length);}
$('> a',this).append(' <span class="'+defaults.classCount+'">('+getCount+')</span>');});}}
function linkOver(){$activeLi=$(this).parent('li');$parentsLi=$activeLi.parents('li');$parentsUl=$activeLi.parents('ul');if(defaults.autoClose==true){autoCloseAccordion($parentsLi,$parentsUl);}
if($('> ul',$activeLi).is(':visible')){$('ul',$activeLi).slideUp(defaults.speed);$('a',$activeLi).removeClass(classActive);}else{$(this).siblings('ul').slideToggle(defaults.speed);$('> a',$activeLi).addClass(classActive);}
if(defaults.saveState==true){createCookie(defaults.cookie,obj,classActive);}}
function linkOut(){}
function menuOver(){}
function menuOut(){if(defaults.menuClose==true){$objSub.slideUp(defaults.speed);$('a',obj).removeClass(classActive);createCookie(defaults.cookie,obj,classActive);}}
function autoCloseAccordion($parentsLi,$parentsUl){$('ul',obj).not($parentsUl).slideUp(defaults.speed);$('a',obj).removeClass(classActive);$('> a',$parentsLi).addClass(classActive);}
function resetAccordion(){$objSub.hide();var $parentsLi=$('a.'+classActive,obj).parents('li');$('> a',$parentsLi).addClass(classActive);$allActiveLi=$('a.'+classActive,obj);$($allActiveLi).siblings('ul').show();}});function checkCookie(cookieId,obj,classActive){var cookieVal=$.cookie(cookieId);if(cookieVal!=null){var activeArray=cookieVal.split(',');$.each(activeArray,function(index,value){var $cookieLi=$('li:eq('+value+')',obj);$('> a',$cookieLi).addClass(classActive);var $parentsLi=$cookieLi.parents('li');$('> a',$parentsLi).addClass(classActive);});}}
function createCookie(cookieId,obj,classActive){var activeIndex=[];$('li a.'+classActive,obj).each(function(i){var $arrayItem=$(this).parent('li');var itemIndex=$('li',obj).index($arrayItem);activeIndex.push(itemIndex);});$.cookie(cookieId,activeIndex,{path:'/'});}};})(jQuery);